server:
  port: 8888

spring:
  cloud:
    config:
      label: develop
      server:
        git:
          uri: https://github.com/lukaszrys/savemaker-config
          basedir: target/config

security:
  user:
    password: ${CONFIG_PASSWORD:password}